export type Spell = { code: string; name: string; desc: string; cost: number; item: string; basic?: boolean };

export const SPELLS: Spell[] = [
  { code: "ZAP", name: "Relâmpago", desc: "Dispara um relâmpago pelas pontas dos dedos contra criaturas sem defesa mágica.", cost: 4, item: "Nenhum", basic: true },
  { code: "HOT", name: "Bola de Fogo", desc: "Cria uma bola de fogo que causa queimaduras sérias no alvo.", cost: 4, item: "Nenhum", basic: true },
  { code: "FOF", name: "Campo de Força", desc: "Cria uma barreira mágica e física sob o controle do conjurador.", cost: 4, item: "Nenhum", basic: true },
  { code: "WAL", name: "Parede Invisível", desc: "Cria uma parede invisível imune a projéteis e criaturas.", cost: 4, item: "Nenhum", basic: true },
  { code: "LAW", name: "Controle da Vontade", desc: "Controla por pouco tempo uma criatura não inteligente.", cost: 4, item: "Nenhum", basic: true },
  { code: "DUM", name: "Descoordenação", desc: "Deixa a criatura desastrada, fazendo-a soltar objetos e armas.", cost: 4, item: "Nenhum", basic: true },
  { code: "BIG", name: "Gigantismo", desc: "Aumenta o corpo e a força do conjurador em até três vezes.", cost: 2, item: "Nenhum" },
  { code: "WOK", name: "Escudo de Moeda", desc: "Transforma uma moeda em um escudo invisível contra armas normais.", cost: 1, item: "Moeda de algum tipo" },
  { code: "DOP", name: "Destrancar", desc: "Destranca portas fechadas por chave ou ferrolho, mas não selos mágicos.", cost: 2, item: "Nenhum" },
  { code: "RAZ", name: "Lâmina Afiada", desc: "Dobra o dano causado por uma arma de fio.", cost: 1, item: "Cera de abelha" },
  { code: "SUS", name: "Suspeita", desc: "Revela armadilhas e indica a melhor proteção contra elas.", cost: 2, item: "Nenhum" },
  { code: "SIX", name: "Seis Imagens", desc: "Cria cinco cópias espelhadas que confundem o inimigo.", cost: 2, item: "Nenhum" },
  { code: "JIG", name: "Dança Irresistível", desc: "Faz o alvo dançar enquanto a flauta for tocada.", cost: 1, item: "Pequena flauta de bambu" },
  { code: "GOB", name: "Criar Goblins", desc: "Transforma dentes de goblins em servos sob seu comando.", cost: 1, item: "Dentes de goblins" },
  { code: "YOB", name: "Criar Gigante", desc: "Cria um gigante de quatro metros para lutar ou realizar feitos de força.", cost: 1, item: "Dente de gigante" },
  { code: "GUM", name: "Cola Mágica", desc: "Torna a cola instantaneamente forte para prender criaturas.", cost: 1, item: "Vidro de cola" },
  { code: "HOW", name: "Caminho Seguro", desc: "Guia por intuição até a saída ou defesa mais segura.", cost: 2, item: "Nenhum" },
  { code: "DOC", name: "Cura Potencializada", desc: "Potencializa uma poção medicinal para curar totalmente quem a beber.", cost: 1, item: "Poção medicinal" },
  { code: "DOZ", name: "Lentidão", desc: "Reduz movimentos e reações do alvo a um sexto da velocidade.", cost: 2, item: "Nenhum" },
  { code: "DUD", name: "Tesouro Ilusório", desc: "Cria uma ilusão de riquezas para distrair, subornar ou pagar.", cost: 2, item: "Nenhum" },
  { code: "MAG", name: "Dissipar Magia", desc: "Neutraliza e dispersa a maioria das magias agressoras.", cost: 2, item: "Nenhum" },
  { code: "POP", name: "Pedras Explosivas", desc: "Carrega pedrinhas para explodirem ao serem arremessadas.", cost: 1, item: "Pedrinhas" },
  { code: "FAL", name: "Queda de Pena", desc: "Deixa o corpo leve para flutuar e pousar suavemente.", cost: 2, item: "Nenhum" },
  { code: "DIM", name: "Confusão", desc: "Confunde temporariamente a mente de uma criatura agressora.", cost: 2, item: "Nenhum" },
  { code: "FOG", name: "Escuridão", desc: "Escurece um cômodo fechado para todos, menos o conjurador.", cost: 2, item: "Nenhum" },
  { code: "MUD", name: "Areia Movediça", desc: "Cria um poço de areia movediça para engolir quem pisar.", cost: 1, item: "Grãos de areia" },
  { code: "NIF", name: "Fedor Nauseante", desc: "Enche o ar com um odor que faz criaturas com olfato vomitarem.", cost: 1, item: "Tampões de nariz" },
  { code: "TEL", name: "Ler Mentes", desc: "Revela intenções, fraquezas e segredos de criaturas inteligentes.", cost: 1, item: "Solidéu de pano" },
  { code: "GAK", name: "Pavor", desc: "Induz medo e pânico terríveis na mente do oponente.", cost: 1, item: "Máscara negra" },
  { code: "SAP", name: "Desmoralizar", desc: "Reduz a vontade do oponente de continuar lutando.", cost: 2, item: "Nenhum" },
  { code: "GOD", name: "Simpatia", desc: "Faz criaturas próximas gostarem do conjurador e oferecerem ajuda.", cost: 1, item: "Joia de ouro" },
  { code: "KIN", name: "Cópia do Inimigo", desc: "Cria uma cópia exata da criatura para lutar contra a original.", cost: 1, item: "Espelho de ouro" },
  { code: "PEP", name: "Força Ardente", desc: "Duplica ou triplica temporariamente a força do conjurador.", cost: 1, item: "Poção de água de fogo" },
  { code: "ROK", name: "Petrificar", desc: "Transforma a criatura atingida em uma estátua de pedra.", cost: 1, item: "Pó de pedra especial" },
  { code: "SUN", name: "Joia do Sol", desc: "Produz luz intensa para cegar inimigos ou iluminar locais escuros.", cost: 1, item: "Joia do sol amarela" },
  { code: "YAP", name: "Língua dos Animais", desc: "Permite entender e falar com a maioria dos animais.", cost: 1, item: "Peruca verde" },
  { code: "KID", name: "Ilusão Bestial", desc: "Cria uma ilusão realista para criaturas não inteligentes.", cost: 1, item: "Bracelete de osso" },
  { code: "RAP", name: "Línguas Não Humanas", desc: "Permite falar idiomas de goblins, orcs e outros povos.", cost: 1, item: "Peruca verde" },
  { code: "ZIP", name: "Teletransporte", desc: "Teletransporta por uma curta distância através de materiais pouco densos.", cost: 1, item: "Anel de metal verde" },
  { code: "FAR", name: "Visão do Futuro", desc: "Mostra no cristal visões do futuro próximo.", cost: 1, item: "Orbe de cristal" },
  { code: "RES", name: "Ressurreição Breve", desc: "Ressuscita temporariamente um humanoide para responder perguntas.", cost: 1, item: "Água benta" },
  { code: "HUF", name: "Rajada Devastadora", desc: "Emite um vento capaz de derrubar criaturas e mover objetos.", cost: 1, item: "Corneta dos ventos" },
  { code: "FIX", name: "Paralisar", desc: "Congela objetos ou oponentes no lugar até o conjurador se afastar.", cost: 1, item: "Cajado de muda de carvalho" },
  { code: "NAP", name: "Sono Profundo", desc: "Hipnotiza e faz criaturas vivas caírem em sono profundo.", cost: 1, item: "Pêndulo de bronze" },
  { code: "ZEN", name: "Levitação", desc: "Permite levitar e flutuar no ar à altura desejada.", cost: 1, item: "Medalhão de gemas preciosas" },
  { code: "YAZ", name: "Invisibilidade", desc: "Torna o conjurador invisível a criaturas de inteligência mediana.", cost: 1, item: "Anel de pérola" },
  { code: "NIP", name: "Supervelocidade", desc: "Permite pensar, falar, mover-se e lutar três vezes mais rápido.", cost: 1, item: "Pó amarelo" },
  { code: "ZED", name: "Magia Suprema", desc: "A magia mais misteriosa e poderosa do mundo, de efeitos desconhecidos.", cost: 7, item: "Nenhum" },
];
